name: GitHub Actions Test

on:
  push:
    branches:
      - master  # branch name

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python and system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip make build-essential

    - name: Install Python dependencies
      run: |
        pip install scikit-surprise  # If you have any other dependencies, specify them here or use requirements.txt
